
### USERS ###
GET http://localhost:3001/api/1c0b36fb-3f28-4824-bc12-3a45d75bc1a7/ HTTP/1.1
content-type: application/json

### ACCOUNTS ###

GET http://localhost:3001/api/1c0b36fb-3f28-4824-bc12-3a45d75bc1a7/accounts/ HTTP/1.1
content-type: application/json

###
POST http://localhost:3001/api/1c0b36fb-3f28-4824-bc12-3a45d75bc1a7/accounts/ HTTP/1.1
content-type: application/json

{
    "name": "New account",
    "balance": 999
}
###
PUT http://localhost:3001/api/1c0b36fb-3f28-4824-bc12-3a45d75bc1a7/accounts/d9564be0-7b73-4d68-983b-845c91cf72a8 HTTP/1.1
content-type: application/json

{    "name": "Chnaged Name",
    "balance": 55555
}
###
DELETE http://localhost:3001/api/1c0b36fb-3f28-4824-bc12-3a45d75bc1a7/accounts/d9564be0-7b73-4d68-983b-845c91cf72a8 HTTP/1.1
content-type: application/json

### TRANSACTIONS ###
GET http://localhost:3001/api/1c0b36fb-3f28-4824-bc12-3a45d75bc1a7/transactions HTTP/1.1
content-type: application/json
###
GET http://localhost:3001/api/1c0b36fb-3f28-4824-bc12-3a45d75bc1a7/transactions/bb6156db-60f0-44cf-9e7f-9dbeb74d1a3a HTTP/1.1
content-type: application/json

###
POST http://localhost:3001/api/1c0b36fb-3f28-4824-bc12-3a45d75bc1a7/transactions/bb6156db-60f0-44cf-9e7f-9dbeb74d1a3a HTTP/1.1
content-type: application/json

{
   "transaction_date": "2025-03-25",
    "payee": "new payee",
    "category_id": "5f946a79-7aa5-4c4a-9478-7ccca3ffc9a1",
    "memo": "",
    "amount": 100
}

###
PUT http://localhost:3001/api/1c0b36fb-3f28-4824-bc12-3a45d75bc1a7/transactions/b0c32286-d391-43b4-b1f4-2a1336c697f9 HTTP/1.1
content-type: application/json

{
   "transaction_date": "2025-03-25",
    "payee": "updated payee",
    "category_id": "5f946a79-7aa5-4c4a-9478-7ccca3ffc9a1",
    "memo": "",
    "amount": 7777
}
###
DELETE http://localhost:3001/api/1c0b36fb-3f28-4824-bc12-3a45d75bc1a7/transactions/ HTTP/1.1
content-type: application/json

{
   "transaction_ids": ["b0c32286-d391-43b4-b1f4-2a1336c697f9"]
}
### CATEGORIES ###
GET http://localhost:3001/api/1c0b36fb-3f28-4824-bc12-3a45d75bc1a7/categories/ HTTP/1.1
content-type: application/json
###
GET http://localhost:3001/api/1c0b36fb-3f28-4824-bc12-3a45d75bc1a7/categories/all HTTP/1.1
content-type: application/json

###
GET http://localhost:3001/api/1c0b36fb-3f28-4824-bc12-3a45d75bc1a7/categories/ready-to-assign HTTP/1.1
content-type: application/json

###
POST http://localhost:3001/api/1c0b36fb-3f28-4824-bc12-3a45d75bc1a7/categories/ HTTP/1.1
content-type: application/json

{
    "category_name": "new category"
}

###
PUT http://localhost:3001/api/1c0b36fb-3f28-4824-bc12-3a45d75bc1a7/categories/c0b5b76c-5d7f-4fba-9546-cf904507627c HTTP/1.1
content-type: application/json

{
    "category_name": "updated category",
    "assigned": 20
}

###
DELETE http://localhost:3001/api/1c0b36fb-3f28-4824-bc12-3a45d75bc1a7/categories/ HTTP/1.1
content-type: application/json

{
    "category_ids": ["c0b5b76c-5d7f-4fba-9546-cf904507627c"]
}