# POST http://localhost:3001/api/auth/sign-in HTTP/1.1
# content-type: application/json

# {
#     "email": "user2@mail.com",
#     "password": "1234"
# }

# GET http://localhost:3001/api/15230c93-4c13-4a71-baa1-77f11408684d/accounts/ HTTP/1.1

# DELETE http://localhost:3001/api/15230c93-4c13-4a71-baa1-77f11408684d/accounts/d2468217-ac0a-4487-8a11-5de6644c275e HTTP/1.1

# PUT http://localhost:3001/api/15230c93-4c13-4a71-baa1-77f11408684d/accounts/3e488504-31fd-466a-85f5-33cdbf8fea3e HTTP/1.1
# content-type: application/json

# {
#     "name": "Changed Name",
#     "balance": "55555"
# }

# POST http://localhost:3001/api/15230c93-4c13-4a71-baa1-77f11408684d/accounts/ HTTP/1.1
# content-type: application/json

# {
#     "name": "New acc",
#     "balance": "999"
# }


# GET http://localhost:3001/api/15230c93-4c13-4a71-baa1-77f11408684d/transactions/3e488504-31fd-466a-85f5-33cdbf8fea3e HTTP/1.1

GET http://localhost:3001/api/15230c93-4c13-4a71-baa1-77f11408684d/transactions/ HTTP/1.1

# POST http://localhost:3001/api/15230c93-4c13-4a71-baa1-77f11408684d/transactions/3e488504-31fd-466a-85f5-33cdbf8fea3e HTTP/1.1
# content-type: application/json

# {
#     "date": "2010-12-20",
#     "payee": "SHOP",
#     "category": "SHOP",
#     "memo": "fsrg",
#     "amount": "999",
#     "cleared": "true"
# }

# PUT http://localhost:3001/api/15230c93-4c13-4a71-baa1-77f11408684d/transactions/b379526d-c8f5-4463-8296-1301a0ba2c0e HTTP/1.1
# content-type: application/json

# {
#     "date": "2025-12-20",
#     "payee": "PJKK",
#     "category": "PJKK",
#     "memo": "fsrg",
#     "amount": "55533",
#     "cleared": "true"
# }


# DELETE  http://localhost:3001/api/15230c93-4c13-4a71-baa1-77f11408684d/transactions/b379526d-c8f5-4463-8296-1301a0ba2c0e HTTP/1.1
