POST http://localhost:3001/api/4bc5a1d7-16ed-4ed8-9a2e-6b4b8332e38c/reports/spending-breakdown HTTP/1.1  
content-Type: application/json  

{
    "startDate": "2024-12",
    "endDate": "2025-02",
    "categories": [
        "b3ebfb19-ff71-4410-9586-f792a9a98b91",
        "1f695803-f553-4b84-bb8f-8017a3cfca6e",
        "401771a6-6ea6-4468-891a-b6ff4784ffab",
        "7f26a33c-5c93-45a6-a1a1-f69947389b15"
    ],
    "accounts": [
        "dcd70c3e-4546-4714-9e96-0ecf601e227b",
        "95d93c43-f7fd-4d5c-ab3b-84072beeaa95"
    ]
}

# "spendingsBreakdown": {
#     "spendingsByCategories": [
#       {
#         "x": "Category 2\n87878 $\n99%",
#         "y": "99",
#         "color": "#681c1b",
#         "category_name": "Category 2",
#         "amount": "87878",
#         "percent": "99"
#       },
#       {
#         "x": "Category 1\n500 $\n1%",
#         "y": "1",
#         "color": "#2137d0",
#         "category_name": "Category 1",
#         "amount": "500",
#         "percent": "1"
#       },
#       {
#         "x": "Category 3\n474 $\n1%",
#         "y": "1",
#         "color": "#c5f606",
#         "category_name": "Category 3",
#         "amount": "474",
#         "percent": "1"
#       }
#     ],
#     "spendingStats": {
#       "avg_monthly_spending": "29617.33",
#       "avg_daily_spending": "29617.00",
#       "most_frequent_category_name": "Category 3",
#       "most_frequent_category_transactions": "1",
#       "largest_outflow_category": "Category 2",
#       "largest_outflow_amount": 87878
#     }
#   }

# POST http://localhost:3001/api/4bc5a1d7-16ed-4ed8-9a2e-6b4b8332e38c/accounts/ HTTP/1.1
# content-type: application/json

# {
#     "name": "New acc",
#     "balance": "999"
# }

# GET http://localhost:3001/api/15230c93-4c13-4a71-baa1-77f11408684d/category-groups HTTP/1.1

# POST http://localhost:3001/api/15230c93-4c13-4a71-baa1-77f11408684d/category-groups HTTP/1.1  
# Content-Type: application/json  

# {  
#     "name": "Health & Fitness"  
# }

# PUT http://localhost:3001/api/15230c93-4c13-4a71-baa1-77f11408684d/category-groups/37d24069-bb4f-430b-9fc0-5f4e06af77a6 HTTP/1.1  
# Content-Type: application/json  

# {  
#     "name": "Updated Group Name"  
# }


# DELETE http://localhost:3001/api/15230c93-4c13-4a71-baa1-77f11408684d/category-groups/bcb543c7-213e-48d4-8878-e41bd4b810d9 HTTP/1.1

#GET http://localhost:3001/api/15230c93-4c13-4a71-baa1-77f11408684d/category-groups/a62fede7-17ed-4aff-8de9-d9476f794053/categories HTTP/1.1

# POST http://localhost:3001/api/15230c93-4c13-4a71-baa1-77f11408684d/category-groups/bcb543c7-213e-48d4-8878-e41bd4b810d9/categories HTTP/1.1  
# Content-Type: application/json  

# {  
#     "name": "Groceries"
# }

# PUT http://localhost:3001/api/15230c93-4c13-4a71-baa1-77f11408684d/category-groups/bcb543c7-213e-48d4-8878-e41bd4b810d9/categories/d05b49c1-c8f1-4f75-a3b8-b677f83cd426 HTTP/1.1  
# Content-Type: application/json  

# {  
#     "name": "Updated Category Name",  
#     "assigned": 60000  
# }

# DELETE http://localhost:3001/api/15230c93-4c13-4a71-baa1-77f11408684d/category-groups/bcb543c7-213e-48d4-8878-e41bd4b810d9/categories/d0a55fc5-6732-49f3-940c-23b0a5c53fc3 HTTP/1.1

# GET http://localhost:3001/api/15230c93-4c13-4a71-baa1-77f11408684d/category-groups/a62fede7-17ed-4aff-8de9-d9476f794053/categories/ee6348ec-6815-4350-8d36-6f40b28c427d/target HTTP/1.1

# PUT http://localhost:3001/api/15230c93-4c13-4a71-baa1-77f11408684d/category-groups/a62fede7-17ed-4aff-8de9-d9476f794053/categories/ee6348ec-6815-4350-8d36-6f40b28c427d/target HTTP/1.1  
# Content-Type: application/json  

# {  
#     "targetType": "monthly",  
#     "need": 40000,  
#     "targetDate": "15",  
#     "nextGoal": "refill up to"  
# }

#DELETE http://localhost:3001/api/15230c93-4c13-4a71-baa1-77f11408684d/category-groups/a62fede7-17ed-4aff-8de9-d9476f794053/categories/ee6348ec-6815-4350-8d36-6f40b28c427d/target HTTP/1.1

# POST http://localhost:3001/api/15230c93-4c13-4a71-baa1-77f11408684d/category-groups/a62fede7-17ed-4aff-8de9-d9476f794053/categories/ee6348ec-6815-4350-8d36-6f40b28c427d/target HTTP/1.1  
# Content-Type: application/json  

# {  
#     "targetType": "monthly",  
#     "need": 30000,  
#     "targetDate": "last day",  
#     "nextGoal": "set aside another"  
# }
######################################################################################################################


# POST http://localhost:3001/api/auth/sign-in HTTP/1.1
# content-type: application/json

# {
#     "email": "user2@mail.com",
#     "password": "1234"
# }

# GET http://localhost:3001/api/15230c93-4c13-4a71-baa1-77f11408684d/accounts/ HTTP/1.1

# DELETE http://localhost:3001/api/15230c93-4c13-4a71-baa1-77f11408684d/accounts/d2468217-ac0a-4487-8a11-5de6644c275e HTTP/1.1

# PUT http://localhost:3001/api/15230c93-4c13-4a71-baa1-77f11408684d/accounts/3e488504-31fd-466a-85f5-33cdbf8fea3e HTTP/1.1
# content-type: application/json

# {
#     "name": "Changed Name",
#     "balance": "55555"
# }

# POST http://localhost:3001/api/15230c93-4c13-4a71-baa1-77f11408684d/accounts/ HTTP/1.1
# content-type: application/json

# {
#     "name": "New acc",
#     "balance": "999"
# }


# GET http://localhost:3001/api/15230c93-4c13-4a71-baa1-77f11408684d/transactions/3e488504-31fd-466a-85f5-33cdbf8fea3e HTTP/1.1

# GET http://localhost:3001/api/15230c93-4c13-4a71-baa1-77f11408684d/transactions/ HTTP/1.1

# POST http://localhost:3001/api/15230c93-4c13-4a71-baa1-77f11408684d/transactions/3e488504-31fd-466a-85f5-33cdbf8fea3e HTTP/1.1
# content-type: application/json

# {
#     "date": "2010-12-20",
#     "payee": "SHOP",
#     "category": "SHOP",
#     "memo": "fsrg",
#     "amount": "999",
#     "cleared": "true"
# }

# PUT http://localhost:3001/api/15230c93-4c13-4a71-baa1-77f11408684d/transactions/b379526d-c8f5-4463-8296-1301a0ba2c0e HTTP/1.1
# content-type: application/json

# {
#     "date": "2025-12-20",
#     "payee": "PJKK",
#     "category": "PJKK",
#     "memo": "fsrg",
#     "amount": "55533",
#     "cleared": "true"
# }


# DELETE  http://localhost:3001/api/15230c93-4c13-4a71-baa1-77f11408684d/transactions/b379526d-c8f5-4463-8296-1301a0ba2c0e HTTP/1.1
